### ISSUE TITLE
Commands for world and channel config retrieval

### ISSUE THREAD

**Issue by thaalesalves** [moirairpg/moirai#111]
## Summary
Although we won't add functionality for world and config management on Discord, a retrieval command should be available.

## Details
Implement commands for these functions with the suggested syntax:
`/world get` -> returns all worlds saved in DB and channel configs linked
`/world get <id>` -> returns the world with specified ids and channel configs linked
`/chconf get` -> returns all chconfigs along with their linked worlds
`/chconf get <id>` -> returns the specified chconfig along with its linked worlds

**Comment by thaalesalves** [comment]
Or this syntax?
`/get world`
`/get world <id>`
`/get chconf`
`/get chconf <id>`

**Comment by MagicShel** [comment]
I don't like `/get`

I might prefer `/world list` which would list all public worlds plus all worlds the user owns?

Same with `/chconf list`.

These lists wouldn't have to be comprehensive objects. Just the ID and enough to describe it (I presume these lists could get quite long, so an id and summary description would be idea - might have to create a field for that.  Same for personas.).

**Comment by thaalesalves** [comment]
I'll create a prototype that prints everything and we can go about trimming what needs to be trimmed.

**Comment by thaalesalves** [comment]
And about list, lorebook is `/lb get`. Should it be `list` as well?

**Comment by MagicShel** [comment]
So yes I prefer list there, as well. But in my head the only optional field here is the text of the lbe itself, so why not just include it? So in this case it wouldn't be a summary, just the full data. So I'm not sure if it's worth keeping the current syntax to show a semantic difference.

**Comment by thaalesalves** [comment]
Not sure I understand what you mean

**Comment by MagicShel** [comment]
I mean as I described above list would show a summary of the data and if you want all the specifics then you get<id>. In this case, I'm questioning whether we would bother doing that summary or just return the whole object. Or maybe summary is for later and for now list just returns the whole thing.

**Comment by thaalesalves** [comment]
I see, so you're suggesting having both `/world list` and `/chconf list` and then `/get <attr>`? Or is it `/world get <attr>` and `/chconf get <attr>`? Aren't these too many commands doing basically the same thing?

As world and chconf are bound to a channel, running something like
`/get world` -> returns the whole thing
`/get chconf` -> same thing but for chconf
`/get persona` -> returns just the persona
`/get model` -> returns model settings


this would be a bit of a pita to implement, but that could even expand it to things like
`/get temperature`
`/get thresholds`
`/get lorebook` (as a lorebook is also attached to a specific channel)

and the like, with the same command having a flexible usage

**Comment by MagicShel** [comment]
No.... I don't like /get at all. In my comment I meant /world list instead of /world get
