### ISSUE TITLE
Author mode

### ISSUE THREAD

**Issue by MagicShel** [moirairpg/moirai#114]
## Summary
Use AI to tell a continuous story with direction from user
## Details
This is essentially chat mode but with some unneeded things stripped out that aren't needed.
### Behavior
In this mode, there is no need to identify different users or retain previous direction, so we reclaim some room for context by passing only the most recent user message. We also strip out any "foo said:" that gets injected elsewhere and identify assistant/user by whether the bot said the message or someone else.

**Comment by thaalesalves** [comment]
Migrated to JIRA.
