### ISSUE TITLE
FEATURE: quick-lore

### ISSUE THREAD

**Issue by MagicShel** [moirairpg/moirai#137]
## Summary
Fast commands to update specially handled lore.
## Details
Have 1 (or possibly 2) special lore cases that are very fast to view & update with a slash command.
Suggestions:
- /note
- /remember
### Behavior
/note would display the current note in an ephemeral message.
/note <text to insert into context> would replace the note with the new text.

The location of this insert is undetermined at this point.
Options:
- Just above the personality
- Just below the personality
- Just above the last user message
- Just below the last user message
- Just above the last message (regardless of whether user or assistant)
- Very last message (not sure this will work, but maybe as a system message)
- Have an optional insertion point parameter that allows the user to configure number of messages up from the bottom
  - While this is more flexible, it takes away options like placing it relative to the personality or last user message unless we do a lot of custom coding. I'm not at all convinced this would be worth the effort.

**Comment by thaalesalves** [comment]
Given the current data model of lorebooks, how would that work? We'd need to add more flags to the table, which would make it more generic than just a lorebook. Doesn't this fit better on its own table? The current data model of lorebooks has nothing but name, regex and description. How would that fit what we have?

**Comment by MagicShel** [comment]
It could be in a separate table. We can talk about the best implementation. It could be a special lore entry with a special regex key, or it could be on a separate table without a regex key. But I see a need for at least one possibly two of these. I don't want to go overboard.

**Comment by thaalesalves** [comment]
I agree that both are necessities, and I'd add /memory if that doesn't cover your suggestions already.

**Comment by MagicShel** [comment]
The way I have it in my head, /note is near the front, taking inspiration from the author's note. /memory would sort of take the place of the memory. I don't know if we need both, but I'm certainly not opposed. I just want a really quick command to make it remember key details because the AI seems to have a really limited recall.

`/note We're in a club. There is a group stalking Lily. Madison is using her as bait to lure them out.` That's super helpful because after way too few messages the AI forgets what the scene is even about.

Having a /memory as well would be good if we find two buckets works better than one. Testing will determine whether it's a meaningless option that only confuses users or is a good feature that must be kept. But the feature has to be developed to test it, so I'm all for it.

**Comment by thaalesalves** [comment]
Migrated to JIRA.
