### ISSUE TITLE
Bug Fix: DB entries send as user role

### ISSUE THREAD

**Issue by MagicShel** [moirairpg/moirai#48]
## Summary
Currently the DungeonMasterUseCase adds database entries to the message queue, which results in them being assigned the `user` role when sent to ChatGPT. These entries might work better if they were assigned a `system` role.

## Details
I think we might want to create an internal Message object. We don't want to have another Message object on top of the JDA Message object, so let's call it MessageData for now and hopefully think up a better name.

MessageData fields:
- originatorId: Optional<String> (if selfId, this would be an `assistant` message. If other discordId, this would be a `user` message. If empty a `system` message.
- content: String
- ?? (anything else that might be userful?)

### Behavior

**Comment by thaalesalves** [comment]
The roles problem is fixed with the PR linked. We can reopen this issue because of the difference in implementation and this new object, to discuss how they would work.

**Comment by thaalesalves** [comment]
Reopening issue to define more about MessageData.

**Comment by thaalesalves** [comment]
Will be part of #64
