### ISSUE TITLE
An editable modal with [ Accept | Retry | Cancel ] options

### ISSUE THREAD

**Issue by MagicShel** [moirairpg/moirai#53]
## Summary
A GM-assist mode where a GM (or the player tagging the bot) get's a popup modal containing the text of the AI response where they can accept (possibly after editing or completely rewriting), request a retry, or even just cancel to go back and edit previous messages before summoning again

## Details
In this mode, summoning the bot would actually invoke a modal which would be populated by the contents of the AI reply.
- When the user clicks accept, the bot says whatever is in the box.
- If the user clicks retry, the contents of the modal are cleared and with another call to the AI (might require closing modal and opening new one)
- If the user clicks cancel, the bot does nothing.
### Behavior

**Comment by thaalesalves** [comment]
Implemented with #77 and #72
