### ISSUE TITLE
Re-engineering of the entire message flow

### ISSUE THREAD

**Issue by thaalesalves** [moirairpg/moirai#64]
## Summary
Separation of input and output mechanics for proper processing. 

## Details
The current architecture the bot has is very simplistic, so it doesn't have separated flows for inputs and outputs. We need top refactor the entire thing so it works in a more flow-friendly and flexible way that is easier to implement changes, maintain and debug. We should also properly document and diagram everything so we always know what's what. 

Following of single-use principle is a must here, so we need to pay attention to those.

**Comment by MagicShel** [comment]
I'm not sure if this should be part of the same story or a different one, but definitely related.
We need to update message handling.

The flow should go something like this:
DM Message received -> Message History is passed into the MessageWrapper along with Prompt, Nudge, Bump, and other system messages
  - On generate:
    - messages formatted/ordered/prioritized/tokens counted
      - messages are scanned for lore mentions and lore loaded/formatted/ordered/prioritized/tokens counted
        - InsertionStrategy is applied to figure out what all will be included in context
          - OrderStrategy is applied to put properly order elements of the context
            - Build the context
              - Build the completion request

**Comment by thaalesalves** [comment]
I think the model you proposed the other day covers both scenarios. I assigned this ticket to you since you're already working on it.

**Comment by thaalesalves** [comment]
Migrated to JIRA.
